### ISSUE TITLE
English readme?

### ISSUE THREAD

**Issue by leleogere** [justleon/MidiTok-Visualizer#3]
Hello,

Thank you for your work, I feel that it can be very useful!

However, you might want to consider adding an English README, so that non-Polish (if it's Polish?) people can easily understand and deploy your tool.

**Comment by justleon** [comment]
Hi @leleogere !
Thanks for the comment. Yeah, we wanted to do that a while ago, but there was not enough time.
I'll try to compose an English readme so that non-polish speakers have a much easier job setting up the project :)

**Comment by mamodrzejewski** [comment]
@leleogere @justleon  done 👌 yes, the README was indeed Polish! 😄

**Comment by justleon** [comment]
Yes, thanks to @mamodrzejewski, the repo now has an English readme.
I believe that the issue can be closed now.

**Comment by leleogere** [comment]
Thank you! I'm gonna have a look at this shortly!
